/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Health check endpoint for container orchestration.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Readiness check endpoint.
         */
        get: operations["ready_check_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/running_line": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get running line data
         * @description Returns programs data for the animated running line on main page.
         */
        get: operations["get_running_line_api_v1_common_running_line_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/common/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global search
         * @description Search across programs and yappers.
         */
        get: operations["global_search_api_v1_common_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/main_page/featured_programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Top Programs
         * @description Get top programs
         */
        get: operations["get_featured_programs_api_v1_main_page_featured_programs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/main_page/programs_leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Programs Leaderboard
         * @description Get programs leaderboard (sorted and ranked by yap_price only)
         */
        get: operations["get_programs_leaderboard_api_v1_main_page_programs_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/main_page/yappers_leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Yappers Leaderboard
         * @description Get yappers leaderboard
         */
        get: operations["get_yappers_leaderboard_api_v1_main_page_yappers_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/main_page/top_tweets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get top tweets
         * @description Returns top performing tweets.
         */
        get: operations["get_top_tweets_api_v1_main_page_top_tweets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/main_page/pool_share_graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pool Share Graph
         * @description Get pool share graph data with historical distribution.
         */
        get: operations["get_pool_share_graph_api_v1_main_page_pool_share_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/main_page/dops_distribution_stats/program/{program_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Program DOPS Stats
         * @description Get distribution stats for a specific program.
         */
        get: operations["get_program_dops_stats_api_v1_main_page_dops_distribution_stats_program__program_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/main_page/dops_distribution_stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Global DOPS Stats
         * @description Get global DOPS distribution statistics.
         */
        get: operations["get_global_dops_stats_api_v1_main_page_dops_distribution_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/program_page/{program_id}/header": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Program Header
         * @description Get program header
         */
        get: operations["get_program_header_api_v1_program_page__program_id__header_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/program_page/{program_id}/top_tweets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Program Top Tweets
         * @description Get program top tweets
         */
        get: operations["get_program_top_tweets_api_v1_program_page__program_id__top_tweets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/program_page/{program_id}/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Program Feed
         * @description Get program feed
         */
        get: operations["get_program_feed_api_v1_program_page__program_id__feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/program_page/{program_id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Program Yappers Leaderboard
         * @description Get program yappers leaderboard
         */
        get: operations["get_program_leaderboard_api_v1_program_page__program_id__leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/program_page/{program_id}/trading_view_header": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trading view header
         * @description Returns trading view header with current price info.
         */
        get: operations["get_trading_view_header_api_v1_program_page__program_id__trading_view_header_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/program_page/{program_id}/daily_stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get daily statistics
         * @description Returns daily statistics charts.
         */
        get: operations["get_daily_stats_api_v1_program_page__program_id__daily_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/program_page/{program_id}/trading_view_chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trading view chart data
         * @description Returns chart data for trading view.
         */
        get: operations["get_trading_view_chart_api_v1_program_page__program_id__trading_view_chart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/program_page/{program_id}/yapper/{twitter_handle}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get yapper stats in program
         * @description Returns yapper statistics within a specific program.
         */
        get: operations["get_yapper_stats_in_program_api_v1_program_page__program_id__yapper__twitter_handle__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/yapper_page/yapper/{yapper_id}/header": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get yapper header
         * @description Returns header data for yapper page.
         */
        get: operations["get_yapper_header_api_v1_yapper_page_yapper__yapper_id__header_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/yapper_page/yapper/{yapper_id}/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get yapper achievements
         * @description Returns achievements earned by yapper.
         */
        get: operations["get_yapper_achievements_api_v1_yapper_page_yapper__yapper_id__achievements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/yapper_page/yapper/{yapper_id}/active_programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get active programs
         * @description Returns programs yapper is actively contributing to.
         */
        get: operations["get_active_programs_api_v1_yapper_page_yapper__yapper_id__active_programs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/yapper_page/yapper/{yapper_id}/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get yapper contributions
         * @description Returns contribution chart data.
         */
        get: operations["get_yapper_contributions_api_v1_yapper_page_yapper__yapper_id__contributions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/yapper_page/yapper/{yapper_id}/spiderchart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get spider chart data
         * @description Returns spider chart metrics for yapper.
         */
        get: operations["get_spider_chart_api_v1_yapper_page_yapper__yapper_id__spiderchart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/yapper_page/yapper/{yapper_id}/charts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get yapper charts
         * @description Returns historical chart data for yapper.
         */
        get: operations["get_yapper_charts_api_v1_yapper_page_yapper__yapper_id__charts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/yapper_page/yapper/{yapper_id}/xfeed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get X (Twitter) feed
         * @description Returns yapper's Twitter feed.
         */
        get: operations["get_x_feed_api_v1_yapper_page_yapper__yapper_id__xfeed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/yapper_page/yapper/{yapper_id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get leaderboard positions
         * @description Returns yapper's positions in different program leaderboards.
         */
        get: operations["get_leaderboard_positions_api_v1_yapper_page_yapper__yapper_id__leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/yapper_page/yapper/global/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get leaderboard positions
         * @description Get leaderboard with optional yapper_id and program_id filters.
         */
        get: operations["get_global_leaderboard_api_v1_yapper_page_yapper_global_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ContributionChartItem */
        ContributionChartItem: {
            /** Timestamp */
            timestamp: number;
            /** Date */
            date?: string | null;
            /** Day Of Week */
            day_of_week: number;
            /** Tweets Count */
            tweets_count: number;
        };
        /** DopsDistributionStatsResponse */
        DopsDistributionStatsResponse: {
            /** Total Dops Distributed */
            total_dops_distributed: number;
            /** Days Left Before New Epoch */
            days_left_before_new_epoch: number;
            /** Today Allocation */
            today_allocation: number;
            winner_data: components["schemas"]["YapperDistributionStats"];
            loser_data: components["schemas"]["YapperDistributionStats"];
            candidate_data: components["schemas"]["YapperDistributionStats"];
        };
        /**
         * GlobalSearchResponseType
         * @enum {string}
         */
        GlobalSearchResponseType: "yapper" | "program" | "tweet";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PoolShareDailyStat */
        PoolShareDailyStat: {
            /**
             * Timestamp
             * @description Unix timestamp
             */
            timestamp: number;
            /**
             * Daily Dops Supply Share
             * @description Share of daily DOPS supply (percentage)
             */
            daily_dops_supply_share: number;
        };
        /** PoolShareItem */
        PoolShareItem: {
            /**
             * Program Id
             * Format: uuid
             * @description Program UUID
             */
            program_id: string;
            /**
             * Program Name
             * @description Program name
             */
            program_name: string;
            /**
             * Program Image Url
             * @description Program logo URL
             */
            program_image_url?: string | null;
            /**
             * Cumulative Tdd
             * @description Total TDD for the requested period
             */
            cumulative_tdd: number;
            /**
             * History
             * @description Historical data points
             */
            history: components["schemas"]["PoolShareDailyStat"][];
        };
        /** ProgramDailyStatsResponse */
        ProgramDailyStatsResponse: {
            /** Avg Tweet Dop Score Chart */
            avg_tweet_dop_score_chart: number[];
            /** Avg Dops Per User Chart */
            avg_dops_per_user_chart: number[];
            /** Daily Tdd Chart */
            daily_tdd_chart: number[];
            /** Daily Dop Score Chart */
            daily_dop_score_chart: number[];
            /** Avg Daily Tweets Chart */
            avg_daily_tweets_chart: number[];
            /** Engagement Chart */
            engagement_chart: number[];
        };
        /** ProgramDopsDistributionStatsResponse */
        ProgramDopsDistributionStatsResponse: {
            /**
             * Program Id
             * Format: uuid
             */
            program_id: string;
            /** Program Name */
            program_name: string;
            /** Program Logo Url */
            program_logo_url: string;
            /** Yap Price */
            yap_price: number;
            /** Top Yappers Count */
            top_yappers_count: number;
            /** Top Yappers Logos Url */
            top_yappers_logos_url: string[];
            /** Tweets Per Day */
            tweets_per_day: number;
            /** Daily Tdd */
            daily_tdd: number;
            /** Avg Tweet Dop Score Chart */
            avg_tweet_dop_score_chart: number[];
            /** Daily Dop Score */
            daily_dop_score: number[];
            /** Avg Dops Per User */
            avg_dops_per_user: number[];
            /** Avg Daily Tweets */
            avg_daily_tweets: number[];
        };
        /** ProgramPageGeneralInfoResponse */
        ProgramPageGeneralInfoResponse: {
            /**
             * Program Id
             * Format: uuid
             */
            program_id: string;
            /** Leaderboard Position */
            leaderboard_position: number;
            /** Token Logo Url */
            token_logo_url: string;
            /** Token Symbol */
            token_symbol: string;
            /** Program Name */
            program_name: string;
            /** Twitter Url */
            twitter_url: string;
            /** Dexscreener Url */
            dexscreener_url: string;
            /** Pumpfun Url */
            pumpfun_url: string;
            /** Website Url */
            website_url: string;
            /** Description */
            description: string;
            /** Fdv */
            fdv: number;
            /** Has Solo Mention Filter */
            has_solo_mention_filter: boolean;
            /** Has Verified Filter */
            has_verified_filter: boolean;
            /** Has Sentiment Filter */
            has_sentiment_filter: boolean;
            /** Has Media Filter */
            has_media_filter: boolean;
            /** Has Consistency Streak Multiplier */
            has_consistency_streak_multiplier: boolean;
            /** Has New Author Multiplier */
            has_new_author_multiplier: boolean;
            /** Has Decay Factor Multiplier */
            has_decay_factor_multiplier: boolean;
            /** Dops Supply Share */
            dops_supply_share: number;
            /** Median Dops Supply Share */
            median_dops_supply_share: number;
            /** Daily Dops Supply */
            daily_dops_supply: number;
            /** Total Tweets */
            total_tweets: number;
            /** Daily Tdd */
            daily_tdd: number;
            /** Total Dops */
            total_dops: number;
            /** Volume */
            volume: number;
            /** Avg Dops Per Tweet */
            avg_dops_per_tweet: number;
        };
        /** ProgramSearchResponse */
        ProgramSearchResponse: {
            /** Name */
            name: string;
            /** Twitter Handle */
            twitter_handle: string;
            /** Logo */
            logo: string;
            /** @default program */
            tag: components["schemas"]["GlobalSearchResponseType"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Twitter Link */
            twitter_link: string;
            /** Daily Tdd */
            daily_tdd: number;
            /** Token Symbol */
            token_symbol: string;
            /** Token Address */
            token_address: string;
        };
        /** ProgramTopTweetResponse */
        ProgramTopTweetResponse: {
            /**
             * Yapper Id
             * Format: uuid
             */
            yapper_id: string;
            /** Yapper Display Name */
            yapper_display_name: string;
            /** Yapper Logo Url */
            yapper_logo_url: string;
            /** Dop Score */
            dop_score: number;
            /** Estimate Dops */
            estimate_dops: number;
            /** Tweet Timestamp */
            tweet_timestamp: number;
            /** Tweet Text */
            tweet_text: string;
            /** Tweet Url */
            tweet_url: string;
            /** Is Authenticated */
            is_authenticated: boolean;
        };
        /** ProgramXFeedItemResponse */
        ProgramXFeedItemResponse: {
            /**
             * Tweet Id
             * Format: uuid
             */
            tweet_id: string;
            /**
             * Program Id
             * Format: uuid
             */
            program_id: string;
            /** Program Name */
            program_name: string;
            /** Avatar Url */
            avatar_url: string;
            /** Username */
            username: string;
            /** Twitter Handle */
            twitter_handle: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** User Twitter Link */
            user_twitter_link: string;
            /** Tweet Link */
            tweet_link: string;
            /** Passed Solo Mention Filter */
            passed_solo_mention_filter: boolean | null;
            /** Passed Verified Filter */
            passed_verified_filter: boolean | null;
            /** Passed Sentiment Filter */
            passed_sentiment_filter: boolean | null;
            /** Passed Media Filter */
            passed_media_filter: boolean | null;
            /** Dop Score */
            dop_score: number;
            /** Estimated Reward In Dops */
            estimated_reward_in_dops: number;
            /** Mindshare */
            mindshare: number;
            /** Yap Text */
            yap_text: string;
            /** Tweet Timestamp */
            tweet_timestamp: number;
            rating: components["schemas"]["Rating"];
            /** Page Count */
            page_count: number;
        };
        /** ProgramYappersLeaderboardItemResponse */
        ProgramYappersLeaderboardItemResponse: {
            /**
             * Yapper Id
             * Format: uuid
             */
            yapper_id: string;
            /** Username */
            username: string;
            /** Avatar Url */
            avatar_url: string;
            /** Rank */
            rank: number;
            /** Rank Change */
            rank_change: number;
            /** Is New */
            is_new: boolean;
            /** Total Dops */
            total_dops: number;
            /** Total Dop Score */
            total_dop_score: number;
            /** Pool Share */
            pool_share: number;
            /** Page Count */
            page_count: number;
        };
        /** ProgramsMainLeaderboardResponse */
        ProgramsMainLeaderboardResponse: {
            /**
             * Program Id
             * Format: uuid
             */
            program_id: string;
            /** Program Name */
            program_name: string;
            /** Program Image Url */
            program_image_url: string;
            /** Is New */
            is_new: boolean;
            /** Yap Price */
            yap_price: number;
            /** Daily Yap Price Chart */
            daily_yap_price_chart: number[];
            /** Dops Supply Share */
            dops_supply_share: number;
            /** Median Dops Supply Share */
            median_dops_supply_share: number;
            /** Daily Dops Supply */
            daily_dops_supply: number;
            /** Avg Dops Per Tweet */
            avg_dops_per_tweet: number;
            /** Fdv */
            fdv: number;
            /** Volume */
            volume: number;
            /** Leaderboard Position */
            leaderboard_position: number;
            /** Tdd */
            tdd: number;
            /** Total Tweets */
            total_tweets: number;
            /** Engagement */
            engagement: number;
            /** Top Yappers */
            top_yappers: number;
            /** Top Yappers Logos */
            top_yappers_logos: string[];
            /** Avg Tweet Dop Score */
            avg_tweet_dop_score: number;
            /** Avg Dops Per User */
            avg_dops_per_user: number;
            /** Has Solo Mention Filter */
            has_solo_mention_filter: boolean;
            /** Has Verified Filter */
            has_verified_filter: boolean;
            /** Has Sentiment Filter */
            has_sentiment_filter: boolean;
            /** Has Media Filter */
            has_media_filter: boolean;
            /** Has Consistency Streak Multiplier */
            has_consistency_streak_multiplier: boolean;
            /** Has New Author Multiplier */
            has_new_author_multiplier: boolean;
            /** Has Decay Factor Multiplier */
            has_decay_factor_multiplier: boolean;
            /** Rank */
            rank: number;
            /** Rank Change */
            rank_change: number;
            /** Page Count */
            page_count: number;
        };
        /**
         * Rating
         * @enum {string}
         */
        Rating: "plankton" | "shrimp" | "fish" | "dolphin" | "whale";
        /** RunningLineItemResponse */
        RunningLineItemResponse: {
            /**
             * Program Id
             * Format: uuid
             */
            program_id: string;
            /** Is New */
            is_new: boolean;
            /** Icon Url */
            icon_url: string;
            /** Program Name */
            program_name: string;
            /** Yap Price */
            yap_price: number;
            /** Yap Price Is Up */
            yap_price_is_up: boolean;
            /** Daily Tdd */
            daily_tdd: number;
            /** Fdv */
            fdv: number;
        };
        /** TopProgramResponse */
        TopProgramResponse: {
            /**
             * Program Id
             * Format: uuid
             */
            program_id: string;
            /** Program Image Url */
            program_image_url: string;
            /** Program Name */
            program_name: string;
            /** Dops Supply Share */
            dops_supply_share: number;
            /** Median Dops Supply Share */
            median_dops_supply_share: number;
            /** Daily Dops Supply */
            daily_dops_supply: number;
            /** Tdd */
            tdd: number;
            /** Fdv */
            fdv: number;
            /** Yap Price */
            yap_price: number;
        };
        /** TopTweetResponse */
        TopTweetResponse: {
            /**
             * Yapper Id
             * Format: uuid
             */
            yapper_id: string;
            /** Yapper Image Url */
            yapper_image_url: string;
            /** Yapper Name */
            yapper_name: string;
            /** Yapper Display Name */
            yapper_display_name: string;
            /** Yapper Dop Score */
            yapper_dop_score: number;
            /**
             * Tweet Id
             * Format: uuid
             */
            tweet_id: string;
            /** Tweet Timestamp */
            tweet_timestamp: number;
            /** Estimated Reward In Dops */
            estimated_reward_in_dops: number;
            /** Yap Text */
            yap_text: string;
            /**
             * Program Id
             * Format: uuid
             */
            program_id: string;
            /** Program Name */
            program_name: string;
            /** Program Image Url */
            program_image_url: string;
            /** Tdd */
            tdd: number;
            /** Daily Tdd Chart */
            daily_tdd_chart: number[];
        };
        /** TradingViewChartResponse */
        TradingViewChartResponse: {
            /**
             * Program Id
             * Format: uuid
             */
            program_id: string;
            /** Timestamps */
            timestamps: number[];
            /** Yap Prices */
            yap_prices: number[];
        };
        /** TradingViewHeaderResponse */
        TradingViewHeaderResponse: {
            /**
             * Program Id
             * Format: uuid
             */
            program_id: string;
            /** Yap Price */
            yap_price: number;
            /** Yap Price Delta */
            yap_price_delta: number;
            /** Ath Token Price */
            ath_token_price: number;
            /** Ath Token Price Delta */
            ath_token_price_delta: number;
            /** Total Dop Score Volume */
            total_dop_score_volume: number;
            /** Avg Dops Per Dop Score */
            avg_dops_per_dop_score: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** YapperAchievement */
        YapperAchievement: {
            /** YapperAchievementType */
            achievement_type: unknown;
            /** Is Obtained */
            is_obtained: boolean;
            /** Timestamp */
            timestamp?: number | null;
            /** Icon Logo Url */
            icon_logo_url: string;
            /** Description */
            description: string;
        };
        /** YapperDistributionStats */
        YapperDistributionStats: {
            /**
             * Yapper Id
             * Format: uuid
             */
            yapper_id: string;
            /** Yapper Display Name */
            yapper_display_name: string;
            /** Yapper Logo Url */
            yapper_logo_url: string;
            /** Total DOPS Earned */
            tde: number;
        };
        /** YapperPageAchievementsResponse */
        YapperPageAchievementsResponse: {
            /**
             * Yapper Id
             * Format: uuid
             */
            yapper_id: string;
            /** Achievements */
            achievements?: components["schemas"]["YapperAchievement"][] | null;
        };
        /** YapperPageActiveProgramResponse */
        YapperPageActiveProgramResponse: {
            /** Rank */
            rank: number;
            /**
             * Program Id
             * Format: uuid
             */
            program_id: string;
            /** Program Name */
            program_name: string;
            /** Program Logo Url */
            program_logo_url: string;
            /** Tdd */
            tdd: number;
            /** Fdv */
            fdv: number;
            /** Dops */
            dops: number;
            /** Yap Price */
            yap_price: number;
            /** Streak In Program */
            streak_in_program: number;
            /** Streak Multiplier In Program */
            streak_multiplier_in_program: number;
            /** Tweets In Program */
            tweets_in_program: number;
            /** Dops Supply Share */
            dops_supply_share: number;
            /** Median Dops Supply Share */
            median_dops_supply_share: number;
            /** Daily Dops Supply */
            daily_dops_supply: number;
            /** Page Count */
            page_count: number;
        };
        /** YapperPageChartsResponse */
        YapperPageChartsResponse: {
            /**
             * Yapper Id
             * Format: uuid
             */
            yapper_id: string;
            /** Avg Dop Score Per Day */
            avg_dop_score_per_day: number[];
            /** Avg Dop Score Per Day Change */
            avg_dop_score_per_day_change: number;
            /** Avg Dops Per Day */
            avg_dops_per_day: number[];
            /** Avg Dops Per Day Change */
            avg_dops_per_day_change: number;
        };
        /** YapperPageContributionsResponse */
        YapperPageContributionsResponse: {
            /**
             * Yapper Id
             * Format: uuid
             */
            yapper_id: string;
            /** Contributions */
            contributions: components["schemas"]["ContributionChartItem"][];
            /** Max Contributions In Period */
            max_contributions_in_period: number;
        };
        /** YapperPageHeaderResponse */
        YapperPageHeaderResponse: {
            /**
             * Yapper Id
             * Format: uuid
             */
            yapper_id: string;
            /** Display Name */
            display_name: string;
            /** Twitter Handle */
            twitter_handle: string;
            /** Logo Url */
            logo_url: string;
            /** Is Authenticated */
            is_authenticated: boolean;
            /** Twitter Link */
            twitter_link: string;
            /** Dop Score */
            dop_score: number;
            /** Total Tweets */
            total_tweets: number;
            /** Avg Yap Price */
            avg_yap_price: number;
            /** Leaderboard Position */
            leaderboard_position: number;
            /** Total Dops */
            total_dops: number;
            /** Engagement */
            engagement: number;
        };
        /** YapperPageLeaderboardItemResponse */
        YapperPageLeaderboardItemResponse: {
            /** Rank */
            rank: number;
            /** Rank Change */
            rank_change: number;
            /**
             * Yapper Id
             * Format: uuid
             */
            yapper_id: string;
            /** Logo Url */
            logo_url: string;
            /** Display Name */
            display_name: string;
            /** Dop Score */
            dop_score: number;
            /** Dop Score Change */
            dop_score_change: number;
            /** Total Dops */
            total_dops: number;
            /** Tweets Count */
            tweets_count: number;
            /** Avg Dops Per Tweet */
            avg_dops_per_tweet: number;
            /** Active Programs */
            active_programs: number;
            /** Active Programs Logos Urls */
            active_programs_logos_urls: string[];
        };
        /** YapperPageLeaderboardResponse */
        YapperPageLeaderboardResponse: {
            /** Leaderboard */
            leaderboard: components["schemas"]["YapperPageLeaderboardItemResponse"][];
            current_yapper: components["schemas"]["YapperPageLeaderboardItemResponse"];
            /** Page Count */
            page_count: number;
        };
        /** YapperPageSpiderChartResponse */
        YapperPageSpiderChartResponse: {
            /**
             * Yapper Id
             * Format: uuid
             */
            yapper_id: string;
            /** Smart */
            smart: number;
            /** Alpha Hunter */
            alpha_hunter: number;
            /** Shitpost */
            shitpost: number;
            /** Creative */
            creative: number;
            /** Engagement */
            engagement: number;
            /** Bullish */
            bullish: number;
            /** Bearish */
            bearish: number;
        };
        /** YapperPageXFeedResponse */
        YapperPageXFeedResponse: {
            /**
             * Tweet Id
             * Format: uuid
             */
            tweet_id: string;
            /** Timestamp */
            timestamp: number;
            /** Estimated Reward In Dops */
            estimated_reward_in_dops: number;
            /**
             * Program Id
             * Format: uuid
             */
            program_id: string;
            /** Program Name */
            program_name: string;
            /** Program Logo Url */
            program_logo_url: string;
            /** Engagement */
            engagement?: number | null;
            /** Reach */
            reach?: number | null;
            /** Text */
            text: string;
            /** Page Count */
            page_count: number;
        };
        /** YapperSearchResponse */
        YapperSearchResponse: {
            /** Name */
            name: string;
            /** Twitter Handle */
            twitter_handle: string;
            /** Logo */
            logo: string;
            /** @default yapper */
            tag: components["schemas"]["GlobalSearchResponseType"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Twitter Link */
            twitter_link: string;
            /** Is Authenticated */
            is_authenticated: boolean;
        };
        /** YapperStatsInProgramResponse */
        YapperStatsInProgramResponse: {
            /**
             * Yapper Id
             * Format: uuid
             */
            yapper_id: string;
            /** Avatar Url */
            avatar_url: string;
            /** Username */
            username: string;
            /** Twitter Handle */
            twitter_handle: string;
            /** Twitter Url */
            twitter_url: string;
            /** Is Verified */
            is_verified: boolean;
            /** Total Dops */
            total_dops: number;
            /** Leaderboard Position */
            leaderboard_position: number;
            /** Avg Dops Per Tweet Chart */
            avg_dops_per_tweet_chart: number[];
            /** Total Dop Score */
            total_dop_score: number;
            /** Pool Share */
            pool_share: number;
            /** Tweet Frequency */
            tweet_frequency: number;
            /** Total Tweets */
            total_tweets: number;
        };
        /** YappersMainLeaderboardActiveProgramData */
        YappersMainLeaderboardActiveProgramData: {
            /**
             * Program Id
             * Format: uuid
             */
            program_id: string;
            /** Program Logo Url */
            program_logo_url: string;
        };
        /** YappersMainLeaderboardData */
        YappersMainLeaderboardData: {
            /**
             * Yapper Id
             * Format: uuid
             */
            yapper_id: string;
            /** Yapper Dipslay Name */
            yapper_dipslay_name: string;
            /** Yapper Logo Url */
            yapper_logo_url: string;
            /** Is New */
            is_new: boolean;
            /** Rank */
            rank?: number | null;
            /** Rank Change */
            rank_change: number;
            /** Total Dops */
            total_dops: number;
            /** Dop Score */
            dop_score: number;
            /** Total Tweets */
            total_tweets: number;
            /** Avg Dops Per Tweet */
            avg_dops_per_tweet: number;
            /** Avg Dops Per Tweet Chart */
            avg_dops_per_tweet_chart: number[];
            /** Tweet Frequency */
            tweet_frequency: number;
            /** Active Programs Count */
            active_programs_count: number;
            /** Active Programs Data */
            active_programs_data: components["schemas"]["YappersMainLeaderboardActiveProgramData"][];
        };
        /** YappersMainLeaderboardResponse */
        YappersMainLeaderboardResponse: {
            /** Page Count */
            page_count: number;
            /** Leaderboard Data */
            leaderboard_data: components["schemas"]["YappersMainLeaderboardData"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_check_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_running_line_api_v1_common_running_line_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunningLineItemResponse"][];
                };
            };
        };
    };
    global_search_api_v1_common_search_get: {
        parameters: {
            query: {
                /** @description Search query */
                query: string;
                /** @description Max results */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["ProgramSearchResponse"] | components["schemas"]["YapperSearchResponse"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_featured_programs_api_v1_main_page_featured_programs_get: {
        parameters: {
            query?: {
                /** @description Sort by field */
                sort_by?: string;
                /** @description Limit */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopProgramResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_programs_leaderboard_api_v1_main_page_programs_leaderboard_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramsMainLeaderboardResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_yappers_leaderboard_api_v1_main_page_yappers_leaderboard_get: {
        parameters: {
            query: {
                /** @description Program ID to filter the yapper leaderboard */
                program_id: string;
                /** @description Page number for pagination */
                page?: number;
                /** @description Items per page */
                limit?: number;
                /** @description Field to sort the yapper leaderboard by */
                sort_by?: string;
                /** @description Sorting direction */
                direction?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YappersMainLeaderboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_top_tweets_api_v1_main_page_top_tweets_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopTweetResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pool_share_graph_api_v1_main_page_pool_share_graph_get: {
        parameters: {
            query?: {
                /** @description Top programs focus */
                top?: "10" | "all";
                /** @description Time range */
                timerange?: "7d" | "30d" | "90d" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolShareItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_program_dops_stats_api_v1_main_page_dops_distribution_stats_program__program_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramDopsDistributionStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_global_dops_stats_api_v1_main_page_dops_distribution_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DopsDistributionStatsResponse"];
                };
            };
        };
    };
    get_program_header_api_v1_program_page__program_id__header_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Program ID */
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramPageGeneralInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_program_top_tweets_api_v1_program_page__program_id__top_tweets_get: {
        parameters: {
            query?: {
                /** @description Items limit */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Program ID */
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramTopTweetResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_program_feed_api_v1_program_page__program_id__feed_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                limit?: number;
                /** @description Search query */
                query?: string | null;
                /** @description Sort by */
                sort_by?: string;
                /** @description Direction */
                direction?: string;
                /** @description Hide zeros */
                hide_zeros?: boolean;
            };
            header?: never;
            path: {
                /** @description Program ID */
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramXFeedItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_program_leaderboard_api_v1_program_page__program_id__leaderboard_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Program ID */
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramYappersLeaderboardItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trading_view_header_api_v1_program_page__program_id__trading_view_header_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Program ID */
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradingViewHeaderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_stats_api_v1_program_page__program_id__daily_stats_get: {
        parameters: {
            query?: {
                /** @description Number of days */
                days?: number;
            };
            header?: never;
            path: {
                /** @description Program ID */
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramDailyStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trading_view_chart_api_v1_program_page__program_id__trading_view_chart_get: {
        parameters: {
            query?: {
                /** @description Time period */
                period?: string;
            };
            header?: never;
            path: {
                /** @description Program ID */
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradingViewChartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_yapper_stats_in_program_api_v1_program_page__program_id__yapper__twitter_handle__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Program ID */
                program_id: string;
                /** @description Twitter handle */
                twitter_handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YapperStatsInProgramResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_yapper_header_api_v1_yapper_page_yapper__yapper_id__header_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yapper UUID */
                yapper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YapperPageHeaderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_yapper_achievements_api_v1_yapper_page_yapper__yapper_id__achievements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yapper UUID */
                yapper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YapperPageAchievementsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_programs_api_v1_yapper_page_yapper__yapper_id__active_programs_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Yapper UUID */
                yapper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YapperPageActiveProgramResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_yapper_contributions_api_v1_yapper_page_yapper__yapper_id__contributions_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                /** @description Yapper UUID */
                yapper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YapperPageContributionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spider_chart_api_v1_yapper_page_yapper__yapper_id__spiderchart_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yapper UUID */
                yapper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YapperPageSpiderChartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_yapper_charts_api_v1_yapper_page_yapper__yapper_id__charts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yapper UUID */
                yapper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YapperPageChartsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_x_feed_api_v1_yapper_page_yapper__yapper_id__xfeed_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Yapper UUID */
                yapper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YapperPageXFeedResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_positions_api_v1_yapper_page_yapper__yapper_id__leaderboard_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Yapper UUID */
                yapper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YapperPageLeaderboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_global_leaderboard_api_v1_yapper_page_yapper_global_leaderboard_get: {
        parameters: {
            query?: {
                /** @description Optional yapper ID to highlight */
                yapper_id?: string | null;
                /** @description Optional program ID to filter */
                program_id?: string | null;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YapperPageLeaderboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
