/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Refresh access token */
        get: operations["AuthController_refresh"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Logout */
        get: operations["AuthController_logout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all user roles */
        get: operations["UsersController_getRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all user permissions by role */
        get: operations["UsersController_getPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users */
        get: operations["UsersController_findAll"];
        put?: never;
        /** Create a new user */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID */
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        /** Delete user */
        delete: operations["UsersController_remove"];
        options?: never;
        head?: never;
        /** Update user */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/users/by-role/{roleName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get users by role name */
        get: operations["UsersController_findUsersByRole"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brokers/get-file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get broker file */
        post: operations["BrokersController_getBrokerFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brokers/update-file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update broker file */
        post: operations["BrokersController_updateBrokerFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brokers/update-and-run-file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update and run broker file */
        post: operations["BrokersController_updateAndRunBrokerFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brokers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all brokers */
        get: operations["BrokersController_findAll"];
        put?: never;
        /** Create a new broker */
        post: operations["BrokersController_create"];
        /** Delete many */
        delete: operations["BrokersController_removeMany"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brokers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get broker by ID */
        get: operations["BrokersController_findOne"];
        put?: never;
        post?: never;
        /** Delete broker */
        delete: operations["BrokersController_remove"];
        options?: never;
        head?: never;
        /** Update broker */
        patch: operations["BrokersController_update"];
        trace?: never;
    };
    "/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get logs by date and category */
        get: operations["LogsController_getLogsByDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/download/{category}/{fileName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LogsController_downloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get lead for partners API */
        get: operations["LeadsController_findAllForPartnersApi"];
        put?: never;
        /** Create a new lead */
        post: operations["LeadsController_create"];
        /** Delete many */
        delete: operations["LeadsController_removeMany"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/export-in-csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate CSV file with leads */
        post: operations["LeadsController_exportInCsv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/downloadExportFile/{fileName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LeadsController_downloadExportFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/viewAutologinImage/{leadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LeadsController_viewAutologinImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/find-by-filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get leads by filters */
        post: operations["LeadsController_findAllByFilters"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/get-statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get leads statistics by filters */
        post: operations["LeadsController_getStatistics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/update-from-autologin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update lead from autologin */
        post: operations["LeadsController_updateLeadFromAutologin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get lead by ID */
        get: operations["LeadsController_findOne"];
        put?: never;
        post?: never;
        /** Delete lead */
        delete: operations["LeadsController_remove"];
        options?: never;
        head?: never;
        /** Update lead */
        patch: operations["LeadsController_update"];
        trace?: never;
    };
    "/leads/confirm-ftd/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Confitm lead ftd */
        get: operations["LeadsController_confirmFtd"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new campaign */
        post: operations["CampaignsController_create"];
        /** Delete many */
        delete: operations["CampaignsController_removeMany"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/find-by-filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get campaigns by filters */
        post: operations["CampaignsController_findByFilters"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/get-statistics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get campaign statistics */
        get: operations["CampaignsController_getStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get campaign by ID */
        get: operations["CampaignsController_findOne"];
        put?: never;
        post?: never;
        /** Delete campaign */
        delete: operations["CampaignsController_remove"];
        options?: never;
        head?: never;
        /** Update campaign */
        patch: operations["CampaignsController_update"];
        trace?: never;
    };
    "/status-mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get status mappings */
        get: operations["StatusMappingsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status-mappings/statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get statuses */
        get: operations["StatusMappingsController_findStatuses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status-mappings/{statusName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update status mapping */
        patch: operations["StatusMappingsController_update"];
        trace?: never;
    };
    "/leads-import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get imported leads by pagination */
        get: operations["LeadsImportController_findAllByPagination"];
        put?: never;
        /** Get leads by filters */
        post: operations["LeadsImportController_importCSV"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lists/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of countries */
        get: operations["ListsController_getCountries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lists/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of languages */
        get: operations["ListsController_getLanguages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autologin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returned html page for autologin */
        get: operations["AutologinController_getAutologinUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autologin/duration-sec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get autologin duration in seconds */
        get: operations["AutologinController_getAutologinDurationSec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update autologin duration in seconds */
        patch: operations["AutologinController_updateAutologinDurationSec"];
        trace?: never;
    };
    "/autologin/is-one-time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get autologin is one time setting */
        get: operations["AutologinController_getAutologinIsOneTime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update autologin is one time setting */
        patch: operations["AutologinController_updateAutologinIsOneTime"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginUserDto: {
            /**
             * Format: email
             * @description User email
             * @example admin@admin.com
             */
            email: string;
            /**
             * @description User password
             * @example admin@admin.com
             */
            password: string;
        };
        ResponseAuthDto: {
            /** @description accessToken */
            accessToken: string;
        };
        CreateUserDto: {
            /** @description User name */
            name: string;
            /**
             * @description Comment
             * @default
             */
            comment: string;
            /**
             * Format: email
             * @description User email
             * @example admin@admin.com
             */
            email: string;
            /**
             * @description User password
             * @example admin@admin.com
             */
            password: string;
            /**
             * @description User role
             * @example ADMIN
             * @enum {string}
             */
            role: "ADMIN" | "MANAGER" | "PARTNER" | "INTEGRATOR" | "BRAND_MANAGER";
            /**
             * @description List of permissions
             * @default []
             */
            permissions: ("full_leads_display" | "full_brokers_display" | "full_partners_display" | "access_to_create_broker")[];
            /** @description Manager ID */
            managerId?: number | null;
        };
        ResponseUserDto: {
            /**
             * @description User ID
             * @example 1
             */
            id: number;
            /** @description User name */
            name: string;
            /**
             * @description Comment
             * @default
             */
            comment: string;
            /**
             * Format: email
             * @description User email
             * @example admin@admin.com
             */
            email: string;
            /**
             * @description User role
             * @example ADMIN
             * @enum {string}
             */
            role: "ADMIN" | "MANAGER" | "PARTNER" | "INTEGRATOR" | "BRAND_MANAGER";
            /**
             * @description List of permissions
             * @default []
             */
            permissions: ("full_leads_display" | "full_brokers_display" | "full_partners_display" | "access_to_create_broker")[];
            /** @description Partner token */
            partnerToken?: string | null;
            /** @description Manager ID */
            managerId?: number | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateUserDto: {
            /** @description User name */
            name?: string;
            /**
             * @description Comment
             * @default
             */
            comment: string;
            /**
             * @description User password
             * @example admin@admin.com
             */
            password?: string;
            /**
             * @description List of permissions
             * @default []
             */
            permissions: ("full_leads_display" | "full_brokers_display" | "full_partners_display" | "access_to_create_broker")[];
            /** @description Manager ID */
            managerId?: number | null;
        };
        GetBrokerFileDto: {
            /** @example 1 */
            brokerId: number;
            /** @enum {string} */
            fileType: "add" | "update";
        };
        ResponseBrokerFileDto: {
            phpCode: string;
        };
        UpdateBrokerFileDto: {
            /** @example 1 */
            brokerId: number;
            /** @enum {string} */
            fileType: "add" | "update";
            phpCode: string;
        };
        ResponseRunBrokerFileDto: {
            success: boolean;
            data?: unknown;
            error?: string;
        };
        CreateBrokerDto: {
            /** @description Broker name */
            name: string;
            /**
             * @description Comment
             * @default
             */
            comment: string;
            /**
             * @description Brand manager ID
             * @example 1
             */
            brandManagerId?: number | null;
        };
        ResponseBrokerDto: {
            /**
             * @description Broker ID
             * @example 1
             */
            id: number;
            /** @description Broker name */
            name: string;
            /**
             * @description Comment
             * @default
             */
            comment: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Broker brand manager */
            brandManager: {
                /** @example 1 */
                id: number;
                name: string;
            } | null;
        };
        UpdateBrokerDto: {
            /** @description Broker name */
            name?: string;
            /**
             * @description Comment
             * @default
             */
            comment: string;
            /**
             * @description Brand manager ID
             * @example 1
             */
            brandManagerId?: number | null;
        };
        CreateLeadDto: {
            /** @description Lead first name */
            firstName: string;
            /** @description Lead last name */
            lastName: string;
            /**
             * Format: email
             * @description Lead email
             */
            email: string;
            /** @description Lead password */
            password?: string | null;
            /** @description Lead phone */
            phone: string;
            /** @description Lead country */
            country: string;
            /** @description Lead language */
            language: string;
            /** @description Lead IP address */
            ip: string;
            /** @description UTM comment */
            utmComment?: string | null;
            /** @description UTM content */
            utmContent?: string | null;
            /** @description Lead funnel */
            funnel?: string | null;
        };
        ResponseCreateLeadDto: {
            /**
             * @description Lead ID
             * @example 1
             */
            id: number;
            /**
             * @description Lead status
             * @example New
             */
            status: string;
            /**
             * Format: uri
             * @description Auto login URL
             */
            autoLoginUrl?: string;
            /** @description Lead FTD */
            ftd?: boolean;
        };
        FindByFiltersLeadsDto: {
            /**
             * @description Lead ID
             * @example 1
             */
            id?: number;
            /**
             * @description Partner ID
             * @example 1
             */
            partnerId?: number | null;
            /**
             * @description Broker ID
             * @example 1
             */
            brokerId?: number | null;
            /**
             * @description Manager ID
             * @example 1
             */
            managerId?: number | null;
            /** @description Broker lead ID */
            brokerLeadId?: string | null;
            /** @description Lead IP address */
            ip?: string;
            /**
             * Format: email
             * @description Lead email
             */
            email?: string;
            /** @description Lead phone */
            phone?: string;
            /** @description Lead funnel */
            funnel?: string | null;
            /**
             * @description Lead status
             * @example New
             */
            status?: string;
            /** @description Lead country */
            country?: string;
            /**
             * @description Campaign ID
             * @example 1
             */
            campaignId?: number | null;
            /**
             * @description Lead FTD
             * @default false
             */
            ftd: boolean;
            /**
             * @description Lead FTD pending
             * @default false
             */
            ftdPending: boolean;
            /**
             * Format: date-time
             * @description Sampling start date
             */
            fromDate?: string;
            /**
             * Format: date-time
             * @description Sampling start date
             */
            toDate?: string;
            /**
             * @description Statistics group
             * @enum {string}
             */
            statisticsGroup?: "rejected" | "invalid";
        };
        FilteredResponseLeadDto: {
            items: {
                /**
                 * @description Lead ID
                 * @example 1
                 */
                id: number;
                /**
                 * @description Lead status
                 * @example New
                 */
                status: string;
                /** @description Broker lead status */
                brokerLeadStatus?: string | null;
                /** @description Lead first name */
                firstName: string;
                /** @description Lead last name */
                lastName: string;
                /**
                 * Format: email
                 * @description Lead email
                 */
                email: string;
                /** @description Lead password */
                password?: string | null;
                /** @description Lead phone */
                phone: string;
                /** @description Lead country */
                country: string;
                /** @description Lead language */
                language: string;
                /** @description Lead IP address */
                ip: string;
                /** @description Lead funnel */
                funnel?: string | null;
                /**
                 * @description Lead FTD
                 * @default false
                 */
                ftd: boolean;
                /**
                 * @description Lead FTD pending
                 * @default false
                 */
                ftdPending: boolean;
                /**
                 * @description Lead FTD pending
                 * @default false
                 */
                ftdWasPending: boolean;
                /** @description Lead FTD date */
                ftdDate: string | null;
                /**
                 * @description Is changeable status
                 * @default true
                 */
                isChangeableStatus: boolean;
                /**
                 * @description Campaign ID
                 * @example 1
                 */
                campaignId?: number | null;
                /** @description UTM comment */
                utmComment?: string | null;
                /** @description UTM content */
                utmContent?: string | null;
                /**
                 * @description Is fraud
                 * @default false
                 */
                isFraud: boolean;
                /**
                 * @description Info by fraud
                 * @default {}
                 */
                isFraudInfo: {
                    ip?: string;
                    useragent?: string;
                    autologinIp?: string;
                    autologinUseragent?: string;
                    autologinFingerprintConfidence?: string;
                    autologinFingerprintCountry?: string;
                    autologinFingerprintLanguage?: string;
                    autologinFingerprintScreenFrame?: string;
                };
                /**
                 * @description Is dublicate
                 * @default false
                 */
                dublicate: boolean;
                /** @description Fingerprint */
                fingerprint?: {
                    [key: string]: unknown;
                } | null;
                /**
                 * @description Partner response
                 * @default {}
                 */
                partnerResponse: {
                    [key: string]: unknown;
                };
                /** @description Broker lead ID */
                brokerLeadId?: string | null;
                /** @description Broker response */
                brokerResponse?: {
                    [key: string]: unknown;
                } | null;
                /** @description Date of lead data update by the broker */
                brokerUpdateDate?: string | null;
                /**
                 * @description Is click auto login
                 * @default false
                 */
                isClickAutoLogin: boolean;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                /** @description Lead partner */
                partner?: {
                    /** @example 1 */
                    id: number;
                    name: string;
                } | null;
                /** @description Lead broker */
                broker?: {
                    /** @example 1 */
                    id: number;
                    name: string;
                } | null;
                /** @description Lead manager */
                manager?: {
                    /** @example 1 */
                    id: number;
                    name: string;
                } | null;
                /** @description Lead campaign */
                campaign?: {
                    /** @example 1 */
                    id: number;
                    name: string;
                } | null;
                /** @description Lead status history */
                leadStatusHistory: {
                    /** @example 1 */
                    id: number;
                    status: string;
                    /** Format: date-time */
                    createdAt: string;
                }[];
            }[];
            meta: {
                totalItems: number;
                itemCount: number;
                itemsPerPage: number;
                totalPages: number;
                currentPage: number;
            };
        };
        GenerateStatisticsResultDto: {
            total: number;
            accepted: number;
            rejected: number;
            deposits: number;
            noAnswer: number;
            noAnswerPercentage: number;
            cr: number;
            invalid: number;
        };
        UpdateLeadFromAutologinDto: {
            /** @example 1 */
            leadId: number;
            fingerprint: {
                [key: string]: unknown;
            };
            screenshotBase64: string;
        };
        FilteredResponseCreateLeadDto: {
            items: {
                /**
                 * @description Lead ID
                 * @example 1
                 */
                id: number;
                /**
                 * @description Lead status
                 * @example New
                 */
                status: string;
                /**
                 * Format: uri
                 * @description Auto login URL
                 */
                autoLoginUrl?: string;
                /** @description Lead FTD */
                ftd?: boolean;
            }[];
            meta: {
                totalItems: number;
                itemCount: number;
                itemsPerPage: number;
                totalPages: number;
                currentPage: number;
            };
        };
        ResponseLeadDto: {
            /**
             * @description Lead ID
             * @example 1
             */
            id: number;
            /**
             * @description Lead status
             * @example New
             */
            status: string;
            /** @description Broker lead status */
            brokerLeadStatus?: string | null;
            /** @description Lead first name */
            firstName: string;
            /** @description Lead last name */
            lastName: string;
            /**
             * Format: email
             * @description Lead email
             */
            email: string;
            /** @description Lead password */
            password?: string | null;
            /** @description Lead phone */
            phone: string;
            /** @description Lead country */
            country: string;
            /** @description Lead language */
            language: string;
            /** @description Lead IP address */
            ip: string;
            /** @description Lead funnel */
            funnel?: string | null;
            /**
             * @description Lead FTD
             * @default false
             */
            ftd: boolean;
            /**
             * @description Lead FTD pending
             * @default false
             */
            ftdPending: boolean;
            /**
             * @description Lead FTD pending
             * @default false
             */
            ftdWasPending: boolean;
            /** @description Lead FTD date */
            ftdDate: string | null;
            /**
             * @description Is changeable status
             * @default true
             */
            isChangeableStatus: boolean;
            /**
             * @description Campaign ID
             * @example 1
             */
            campaignId?: number | null;
            /** @description UTM comment */
            utmComment?: string | null;
            /** @description UTM content */
            utmContent?: string | null;
            /**
             * @description Is fraud
             * @default false
             */
            isFraud: boolean;
            /**
             * @description Info by fraud
             * @default {}
             */
            isFraudInfo: {
                ip?: string;
                useragent?: string;
                autologinIp?: string;
                autologinUseragent?: string;
                autologinFingerprintConfidence?: string;
                autologinFingerprintCountry?: string;
                autologinFingerprintLanguage?: string;
                autologinFingerprintScreenFrame?: string;
            };
            /**
             * @description Is dublicate
             * @default false
             */
            dublicate: boolean;
            /** @description Fingerprint */
            fingerprint?: {
                [key: string]: unknown;
            } | null;
            /**
             * @description Partner response
             * @default {}
             */
            partnerResponse: {
                [key: string]: unknown;
            };
            /** @description Broker lead ID */
            brokerLeadId?: string | null;
            /** @description Broker response */
            brokerResponse?: {
                [key: string]: unknown;
            } | null;
            /** @description Date of lead data update by the broker */
            brokerUpdateDate?: string | null;
            /**
             * @description Is click auto login
             * @default false
             */
            isClickAutoLogin: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Lead partner */
            partner?: {
                /** @example 1 */
                id: number;
                name: string;
            } | null;
            /** @description Lead broker */
            broker?: {
                /** @example 1 */
                id: number;
                name: string;
            } | null;
            /** @description Lead manager */
            manager?: {
                /** @example 1 */
                id: number;
                name: string;
            } | null;
            /** @description Lead campaign */
            campaign?: {
                /** @example 1 */
                id: number;
                name: string;
            } | null;
            /** @description Lead status history */
            leadStatusHistory: {
                /** @example 1 */
                id: number;
                status: string;
                /** Format: date-time */
                createdAt: string;
            }[];
        };
        UpdateLeadDto: {
            /**
             * @description Lead status
             * @example New
             */
            status?: string;
            /**
             * @description Lead FTD
             * @default false
             */
            ftd: boolean;
            /**
             * @description Is changeable status
             * @default true
             */
            isChangeableStatus: boolean;
            /**
             * @description Lead FTD pending
             * @default false
             */
            ftdPending: boolean;
        };
        CreateCampaignDto: {
            /** @description Campaign name */
            name: string;
            /**
             * @description Comment
             * @default
             */
            comment: string;
            /**
             * @description Daily campaign leads CAP
             * @example 5
             */
            dailyCap: number;
            /**
             * @description Partner ID
             * @example 1
             */
            partnerId?: number | null;
            /**
             * @description Broker ID
             * @example 1
             */
            brokerId: number;
            /**
             * @description Manager ID
             * @example 1
             */
            managerId?: number | null;
            /**
             * @description Is campaign active
             * @default true
             */
            isActive: boolean;
            /**
             * @description Funnel
             * @default
             */
            funnel: string;
            /**
             * @description Check funnel
             * @default false
             */
            checkFunnel: boolean;
            /**
             * @description Countries
             * @default []
             * @example [
             *       "EN",
             *       "UA",
             *       "KZ"
             *     ]
             */
            countries: string[];
            /**
             * @description Languages
             * @default []
             * @example [
             *       "en",
             *       "uk",
             *       "kk"
             *     ]
             */
            languages: string[];
            /**
             * @description Is schedule enabled
             * @default false
             */
            isScheduleEnabled: boolean;
            /**
             * @description Timezone
             * @default UTC
             * @example UTC
             */
            timezone: string;
            /**
             * @description Working days and hours
             * @default {}
             * @example {
             *       "mon": {
             *         "start": "09:00",
             *         "end": "18:00"
             *       },
             *       "tue": {
             *         "start": "09:00",
             *         "end": "18:00"
             *       }
             *     }
             */
            workingHours: {
                [key: string]: {
                    start: string;
                    end: string;
                };
            };
        };
        ResponseCampaignDto: {
            /**
             * @description Campaign ID
             * @example 1
             */
            id: number;
            /** @description Campaign name */
            name: string;
            /**
             * @description Comment
             * @default
             */
            comment: string;
            /**
             * @description Daily campaign leads CAP
             * @example 5
             */
            dailyCap: number;
            /**
             * @description Current daily campaign leads count
             * @example 0
             */
            currentDailyCount: number;
            /**
             * @description Is campaign active
             * @default true
             */
            isActive: boolean;
            /**
             * @description Funnel
             * @default
             */
            funnel: string;
            /**
             * @description Check funnel
             * @default false
             */
            checkFunnel: boolean;
            /**
             * @description Countries
             * @default []
             * @example [
             *       "EN",
             *       "UA",
             *       "KZ"
             *     ]
             */
            countries: string[];
            /**
             * @description Languages
             * @default []
             * @example [
             *       "en",
             *       "uk",
             *       "kk"
             *     ]
             */
            languages: string[];
            /**
             * @description Is schedule enabled
             * @default false
             */
            isScheduleEnabled: boolean;
            /**
             * @description Timezone
             * @default UTC
             * @example UTC
             */
            timezone: string;
            /**
             * @description Working days and hours
             * @default {}
             * @example {
             *       "mon": {
             *         "start": "09:00",
             *         "end": "18:00"
             *       },
             *       "tue": {
             *         "start": "09:00",
             *         "end": "18:00"
             *       }
             *     }
             */
            workingHours: {
                [key: string]: {
                    start: string;
                    end: string;
                };
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Campaign partner */
            partner?: {
                /** @example 1 */
                id: number;
                name: string;
            } | null;
            /** @description Campaign broker */
            broker: {
                /** @example 1 */
                id: number;
                name: string;
            };
            /** @description Campaign manager */
            manager?: {
                /** @example 1 */
                id: number;
                name: string;
            } | null;
        };
        FindByFiltersCampaignDto: {
            /** @description Campaign name */
            name?: string;
            /**
             * @description Partner ID
             * @example 1
             */
            partnerId?: number | null;
            /**
             * @description Broker ID
             * @example 1
             */
            brokerId?: number;
            /**
             * @description Manager ID
             * @example 1
             */
            managerId?: number | null;
            /**
             * @description Is campaign active
             * @default true
             */
            isActive: boolean;
            /**
             * @description Countries
             * @default []
             * @example [
             *       "EN",
             *       "UA",
             *       "KZ"
             *     ]
             */
            countries: string[];
            /**
             * @description Languages
             * @default []
             * @example [
             *       "en",
             *       "uk",
             *       "kk"
             *     ]
             */
            languages: string[];
        };
        FilteredResponseCampaignDto: {
            items: {
                /**
                 * @description Campaign ID
                 * @example 1
                 */
                id: number;
                /** @description Campaign name */
                name: string;
                /**
                 * @description Comment
                 * @default
                 */
                comment: string;
                /**
                 * @description Daily campaign leads CAP
                 * @example 5
                 */
                dailyCap: number;
                /**
                 * @description Current daily campaign leads count
                 * @example 0
                 */
                currentDailyCount: number;
                /**
                 * @description Is campaign active
                 * @default true
                 */
                isActive: boolean;
                /**
                 * @description Funnel
                 * @default
                 */
                funnel: string;
                /**
                 * @description Check funnel
                 * @default false
                 */
                checkFunnel: boolean;
                /**
                 * @description Countries
                 * @default []
                 * @example [
                 *       "EN",
                 *       "UA",
                 *       "KZ"
                 *     ]
                 */
                countries: string[];
                /**
                 * @description Languages
                 * @default []
                 * @example [
                 *       "en",
                 *       "uk",
                 *       "kk"
                 *     ]
                 */
                languages: string[];
                /**
                 * @description Is schedule enabled
                 * @default false
                 */
                isScheduleEnabled: boolean;
                /**
                 * @description Timezone
                 * @default UTC
                 * @example UTC
                 */
                timezone: string;
                /**
                 * @description Working days and hours
                 * @default {}
                 * @example {
                 *       "mon": {
                 *         "start": "09:00",
                 *         "end": "18:00"
                 *       },
                 *       "tue": {
                 *         "start": "09:00",
                 *         "end": "18:00"
                 *       }
                 *     }
                 */
                workingHours: {
                    [key: string]: {
                        start: string;
                        end: string;
                    };
                };
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                /** @description Campaign partner */
                partner?: {
                    /** @example 1 */
                    id: number;
                    name: string;
                } | null;
                /** @description Campaign broker */
                broker: {
                    /** @example 1 */
                    id: number;
                    name: string;
                };
                /** @description Campaign manager */
                manager?: {
                    /** @example 1 */
                    id: number;
                    name: string;
                } | null;
            }[];
            meta: {
                totalItems: number;
                itemCount: number;
                itemsPerPage: number;
                totalPages: number;
                currentPage: number;
            };
        };
        UpdateCampaignDto: {
            /** @description Campaign name */
            name?: string;
            /**
             * @description Comment
             * @default
             */
            comment: string;
            /**
             * @description Daily campaign leads CAP
             * @example 5
             */
            dailyCap?: number;
            /**
             * @description Partner ID
             * @example 1
             */
            partnerId?: number | null;
            /**
             * @description Broker ID
             * @example 1
             */
            brokerId?: number;
            /**
             * @description Manager ID
             * @example 1
             */
            managerId?: number | null;
            /**
             * @description Is campaign active
             * @default true
             */
            isActive: boolean;
            /**
             * @description Funnel
             * @default
             */
            funnel: string;
            /**
             * @description Check funnel
             * @default false
             */
            checkFunnel: boolean;
            /**
             * @description Countries
             * @default []
             * @example [
             *       "EN",
             *       "UA",
             *       "KZ"
             *     ]
             */
            countries: string[];
            /**
             * @description Languages
             * @default []
             * @example [
             *       "en",
             *       "uk",
             *       "kk"
             *     ]
             */
            languages: string[];
            /**
             * @description Is schedule enabled
             * @default false
             */
            isScheduleEnabled: boolean;
            /**
             * @description Timezone
             * @default UTC
             * @example UTC
             */
            timezone: string;
            /**
             * @description Working days and hours
             * @default {}
             * @example {
             *       "mon": {
             *         "start": "09:00",
             *         "end": "18:00"
             *       },
             *       "tue": {
             *         "start": "09:00",
             *         "end": "18:00"
             *       }
             *     }
             */
            workingHours: {
                [key: string]: {
                    start: string;
                    end: string;
                };
            };
        };
        ResponseStatusMappingDto: {
            statusName: string;
            externalStatuses: string[];
        };
        LeadsImportResponseDto: {
            total: number;
            imported: number;
            notImported: number;
            notImportedRows: unknown;
        };
        PaginatedLeadImportDto: {
            items: {
                /** @description Lead first name */
                firstName: string;
                /** @description Lead last name */
                lastName: string;
                /**
                 * Format: email
                 * @description Lead email
                 */
                email: string;
                /** @description Lead password */
                password?: string | null;
                /** @description Lead phone */
                phone: string;
                /** @description Lead country */
                country: string;
                /** @description Lead language */
                language: string;
                /** @description Lead IP address */
                ip: string;
                /** @description UTM comment */
                utmComment?: string | null;
                /** @description UTM content */
                utmContent?: string | null;
                /** @description Lead funnel */
                funnel?: string | null;
            }[];
            meta: {
                totalItems: number;
                itemCount: number;
                itemsPerPage: number;
                totalPages: number;
                currentPage: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginUserDto"];
            };
        };
        responses: {
            /** @description User successfully logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseAuthDto"];
                };
            };
            /** @description Incorrect email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully refresh token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseAuthDto"];
                };
            };
            /** @description Incorrect email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No access, authorization required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    UsersController_getPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Object of permissions by role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseUserDto"][];
                };
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description User successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseUserDto"];
                };
            };
            /** @description Invalid data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseUserDto"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User successfully deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description User successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseUserDto"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findUsersByRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users by role name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseUserDto"][];
                };
            };
        };
    };
    BrokersController_getBrokerFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetBrokerFileDto"];
            };
        };
        responses: {
            /** @description File found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseBrokerFileDto"];
                };
            };
            /** @description Broker not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrokersController_updateBrokerFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBrokerFileDto"];
            };
        };
        responses: {
            /** @description Broker file successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrokersController_updateAndRunBrokerFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBrokerFileDto"];
            };
        };
        responses: {
            /** @description Broker file successfully updated and run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseRunBrokerFileDto"];
                };
            };
            /** @description Invalid data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrokersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of brokers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseBrokerDto"][];
                };
            };
        };
    };
    BrokersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBrokerDto"];
            };
        };
        responses: {
            /** @description Broker successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseBrokerDto"];
                };
            };
            /** @description Invalid data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrokersController_removeMany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": number[];
            };
        };
        responses: {
            /** @description Successfully deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrokersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Broker ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Broker found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseBrokerDto"];
                };
            };
            /** @description Broker not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrokersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Broker ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Broker successfully deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Broker not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrokersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Broker ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBrokerDto"];
            };
        };
        responses: {
            /** @description Broker successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseBrokerDto"];
                };
            };
            /** @description Broker not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LogsController_getLogsByDate: {
        parameters: {
            query: {
                /** @description Date in format YYYY-MM-DD */
                date: string;
                /** @description Log category */
                category: "leads" | "brokers";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logs successfully returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        downloadUrl?: string;
                    };
                };
            };
        };
    };
    LogsController_downloadFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category: string;
                fileName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LeadsController_findAllForPartnersApi: {
        parameters: {
            query: {
                "partner-token": string;
                page?: number;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leads founded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilteredResponseCreateLeadDto"];
                };
            };
            /** @description Partner not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LeadsController_create: {
        parameters: {
            query?: never;
            header: {
                "partner-token": string;
                "user-agent": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLeadDto"];
            };
        };
        responses: {
            /** @description Lead successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseCreateLeadDto"];
                };
            };
            /** @description Invalid data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LeadsController_removeMany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": number[];
            };
        };
        responses: {
            /** @description Successfully deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LeadsController_exportInCsv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindByFiltersLeadsDto"];
            };
        };
        responses: {
            /** @description Generated CSV file URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        downloadUrl?: string;
                    };
                };
            };
        };
    };
    LeadsController_downloadExportFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LeadsController_viewAutologinImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LeadsController_findAllByFilters: {
        parameters: {
            query: {
                page: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindByFiltersLeadsDto"];
            };
        };
        responses: {
            /** @description List of leads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilteredResponseLeadDto"];
                };
            };
        };
    };
    LeadsController_getStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindByFiltersLeadsDto"];
            };
        };
        responses: {
            /** @description Statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateStatisticsResultDto"];
                };
            };
        };
    };
    LeadsController_updateLeadFromAutologin: {
        parameters: {
            query?: never;
            header: {
                "user-agent": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLeadFromAutologinDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LeadsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lead found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseLeadDto"];
                };
            };
            /** @description Lead not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LeadsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lead successfully deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lead not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LeadsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLeadDto"];
            };
        };
        responses: {
            /** @description Lead successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseLeadDto"];
                };
            };
            /** @description Lead not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LeadsController_confirmFtd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lead successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lead not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CampaignsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampaignDto"];
            };
        };
        responses: {
            /** @description Campaign successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseCampaignDto"];
                };
            };
            /** @description Invalid data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CampaignsController_removeMany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": number[];
            };
        };
        responses: {
            /** @description Successfully deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CampaignsController_findByFilters: {
        parameters: {
            query: {
                page: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindByFiltersCampaignDto"];
            };
        };
        responses: {
            /** @description List of campaigns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilteredResponseCampaignDto"];
                };
            };
        };
    };
    CampaignsController_getStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateStatisticsResultDto"];
                };
            };
            /** @description Campaign not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CampaignsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Campaign ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseCampaignDto"];
                };
            };
            /** @description Campaign not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CampaignsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Campaign ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign successfully deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Campaign not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CampaignsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Campaign ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCampaignDto"];
            };
        };
        responses: {
            /** @description Campaign successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseCampaignDto"];
                };
            };
            /** @description Campaign not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StatusMappingsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of status mappings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseStatusMappingDto"][];
                };
            };
        };
    };
    StatusMappingsController_findStatuses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of statuses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    StatusMappingsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statusName: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Status mapping successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseStatusMappingDto"];
                };
            };
            /** @description Status mapping not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LeadsImportController_findAllByPagination: {
        parameters: {
            query: {
                page: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of imported leads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLeadImportDto"];
                };
            };
        };
    };
    LeadsImportController_importCSV: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CSV file to import leads */
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description List of leads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadsImportResponseDto"];
                };
            };
        };
    };
    ListsController_getCountries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved the list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    ListsController_getLanguages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved the list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    AutologinController_getAutologinUrl: {
        parameters: {
            query: {
                leadId: string;
                firstName: string;
                autologinUrl?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Html page successfully returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    AutologinController_getAutologinDurationSec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Autologin duration in seconds successfully returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        autologin_duration_sec?: number;
                    };
                };
            };
        };
    };
    AutologinController_updateAutologinDurationSec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    durationSec: number;
                };
            };
        };
        responses: {
            /** @description Autologin duration in seconds successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        autologin_duration_sec?: number;
                    };
                };
            };
        };
    };
    AutologinController_getAutologinIsOneTime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Autologin is one time setting successfully returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        autologin_is_one_time?: boolean;
                    };
                };
            };
        };
    };
    AutologinController_updateAutologinIsOneTime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    isOneTime: boolean;
                };
            };
        };
        responses: {
            /** @description Autologin is one time setting successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        autologin_is_one_time?: boolean;
                    };
                };
            };
        };
    };
}
